version: '3'
services:

  database:
    image: mysql:8
    container_name: database
    profiles: ["database", "full"]
    restart: on-failure
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=listados
    networks:
      - internal

  pulsar:
    image: apachepulsar/pulsar:3.2.0
    container_name: pulsar
    profiles: ["pulsar", "full"]
    restart: on-failure
    ports:
      - "6650:6650"
      - "8080:8080"
    command: ["bin/pulsar", "standalone"]
    healthcheck:
      test: ["CMD", "/bin/pulsar", "admin", "brokers", "healthcheck"]
      interval: 1s
      timeout: 3s
      retries: 10
    networks:
      - internal

  listados:
    container_name: listados
    image: listados
    command: "tail -f /dev/null"
    profiles: ["listados", "full"]
    ports:
      - "5000:5000"
    build:
      context: .
      dockerfile: src/listados/Dockerfile
    env_file: .env
    volumes:
      - ./src:/src
    networks:
      - internal


networks:
  internal:
